[package]
name = "saudi-founding-day"
version = "0.1.0"
description = "Saudi Founding Day Interactive Web App"

# This configuration tells Wasmer how to run the standalone Node.js server
[[module]]
name = "server"
source = "dist/standalone/server.js"
abi = "wasi"

[[command]]
name = "start"
module = "server"
runner = "https://webc.org/runner/node"
annotations = { wagi = "false" }

[fs]
"/public" = "public"
"/dist/standalone/public" = "public"
"/dist/static" = "dist/static"
"/dist/standalone/dist/static" = "dist/static"
